import {
  Mic,
  Headphones,
  PlayCircle,
  Brain,
  UserCheck,
  BarChart3,
  Calendar,
  Shield,
  Database,
  MessageSquare,
  FileText,
  Monitor,
  Video,
} from "lucide-react"

export const apps = [
  {
    name: "Interview Studio",
    icon: <Mic className="text-violet-500" />,
    description: "AI-powered interview recording and management",
    category: "Interview",
    recent: true,
    new: false,
    progress: 100,
  },
  {
    name: "Voice Agent",
    icon: <Headphones className="text-orange-500" />,
    description: "Intelligent voice interviewer with adaptive questioning",
    category: "AI",
    recent: true,
    new: false,
    progress: 100,
  },
  {
    name: "Recording Viewer",
    icon: <PlayCircle className="text-pink-500" />,
    description: "9:16 format interview playback and analysis",
    category: "Analysis",
    recent: true,
    new: false,
    progress: 100,
  },
  {
    name: "AI Insights",
    icon: <Brain className="text-blue-500" />,
    description: "Intelligent analysis and candidate evaluation",
    category: "AI",
    recent: false,
    new: false,
    progress: 100,
  },
  {
    name: "Candidate Manager",
    icon: <UserCheck className="text-red-500" />,
    description: "Comprehensive candidate profile management",
    category: "Management",
    recent: false,
    new: false,
    progress: 100,
  },
  {
    name: "Analytics Dashboard",
    icon: <BarChart3 className="text-fuchsia-500" />,
    description: "Interview performance and success metrics",
    category: "Analytics",
    recent: false,
    new: true,
    progress: 85,
  },
  {
    name: "Session Scheduler",
    icon: <Calendar className="text-teal-500" />,
    description: "Interview scheduling and calendar management",
    category: "Scheduling",
    recent: false,
    new: false,
    progress: 100,
  },
  {
    name: "Security Center",
    icon: <Shield className="text-red-600" />,
    description: "Data protection and compliance management",
    category: "Security",
    recent: false,
    progress: 100,
    new: false,
  },
  {
    name: "Integration Hub",
    icon: <Database className="text-emerald-500" />,
    description: "Connect with HR systems and databases",
    category: "Integration",
    recent: false,
    new: true,
    progress: 70,
  },
  {
    name: "Question Bank",
    icon: <MessageSquare className="text-indigo-500" />,
    description: "AI-generated and custom interview questions",
    category: "Content",
    recent: false,
    new: true,
    progress: 60,
  },
  {
    name: "Report Generator",
    icon: <FileText className="text-amber-500" />,
    description: "Automated interview reports and summaries",
    category: "Reports",
    recent: false,
    new: false,
    progress: 100,
  },
  {
    name: "Live Monitor",
    icon: <Monitor className="text-purple-500" />,
    description: "Real-time interview monitoring and oversight",
    category: "Monitoring",
    recent: false,
    new: false,
    progress: 100,
  },
]

export const recentFiles = [
  {
    name: "Exchange Program Interview - Sarah Chen.mp4",
    app: "Interview Studio",
    modified: "2 hours ago",
    icon: <Video className="text-violet-500" />,
    shared: true,
    size: "124.5 MB",
    collaborators: 3,
  },
  {
    name: "AI Analysis Report - John Smith.pdf",
    app: "AI Insights",
    modified: "Yesterday",
    icon: <Brain className="text-orange-500" />,
    shared: true,
    size: "2.8 MB",
    collaborators: 2,
  },
  {
    name: "Teaching Position Interview - Maria Garcia.mp4",
    app: "Interview Studio",
    modified: "3 days ago",
    icon: <Video className="text-pink-500" />,
    shared: false,
    size: "98.2 MB",
    collaborators: 0,
  },
  {
    name: "Batch Analysis Summary - Week 12.xlsx",
    app: "Analytics Dashboard",
    modified: "Last week",
    icon: <BarChart3 className="text-blue-500" />,
    shared: true,
    size: "5.4 MB",
    collaborators: 4,
  },
  {
    name: "Student Assessment - Physics Dept.pdf",
    app: "Report Generator",
    modified: "2 weeks ago",
    icon: <FileText className="text-red-500" />,
    shared: false,
    size: "12.8 MB",
    collaborators: 0,
  },
  {
    name: "Exchange Program Candidates.csv",
    app: "Candidate Manager",
    modified: "3 weeks ago",
    icon: <UserCheck className="text-fuchsia-500" />,
    shared: true,
    size: "1.3 MB",
    collaborators: 5,
  },
  {
    name: "Interview Session Recordings - Batch 5.zip",
    app: "Recording Viewer",
    modified: "Last month",
    icon: <PlayCircle className="text-teal-500" />,
    shared: false,
    size: "2.1 GB",
    collaborators: 0,
  },
]

export const projects = [
  {
    name: "Spring Exchange Program",
    description: "AI interviews for 150+ exchange program applicants",
    progress: 75,
    dueDate: "June 15, 2025",
    members: 4,
    files: 89,
  },
  {
    name: "Teaching Staff Recruitment",
    description: "Faculty hiring interviews for multiple departments",
    progress: 60,
    dueDate: "July 30, 2025",
    members: 6,
    files: 142,
  },
  {
    name: "Student Assessment - Physics",
    description: "Oral examination replacement for physics students",
    progress: 90,
    dueDate: "May 25, 2025",
    members: 3,
    files: 67,
  },
  {
    name: "Graduate Admissions",
    description: "AI-powered interviews for graduate school applications",
    progress: 40,
    dueDate: "August 10, 2025",
    members: 5,
    files: 203,
  },
]

export const communityPosts = [
  {
    title: "Reduced Cheating by 95% with AI Interviews",
    author: "University of Cambridge",
    likes: 342,
    comments: 28,
    image: "/placeholder.svg?height=300&width=400",
    time: "2 days ago",
  },
  {
    title: "Exchange Program Selection Made Easy",
    author: "Global Education Network",
    likes: 518,
    comments: 47,
    image: "/placeholder.svg?height=300&width=400",
    time: "1 week ago",
  },
  {
    title: "AI Interview Analytics Dashboard",
    author: "TechCorp HR",
    likes: 276,
    comments: 32,
    image: "/placeholder.svg?height=300&width=400",
    time: "3 days ago",
  },
  {
    title: "Student Assessment Revolution",
    author: "MIT Education Lab",
    likes: 189,
    comments: 15,
    image: "/placeholder.svg?height=300&width=400",
    time: "5 days ago",
  },
]

export const groups = [
  {
    id: "1",
    title: "Spring Exchange Program",
    description: "Students applying for spring semester exchange",
    candidates: 45,
    createdAt: "2024-01-15",
    status: "active",
  },
  {
    id: "2",
    title: "Teaching Staff Recruitment",
    description: "Faculty hiring for multiple departments",
    candidates: 28,
    createdAt: "2024-01-10",
    status: "active",
  },
  {
    id: "3",
    title: "Graduate Admissions",
    description: "PhD and Masters program applicants",
    candidates: 67,
    createdAt: "2024-01-05",
    status: "active",
  },
  {
    id: "4",
    title: "Student Assessment - Physics",
    description: "Physics department oral examinations",
    candidates: 23,
    createdAt: "2024-01-20",
    status: "completed",
  },
]
